#Script name- generate_moirai_spatial
#Author- Kanishka Narayan
#Date- 10th August 2020
#Description- Combine different boundaries with MOIRAI land data to get combined shape files

#Load libraries
library(rgdal)
library(raster)
library(sp)
library(sf)
library(dplyr)
library(data.table)
library(nngeo)
library(smoothr)


#Create directories to store files
dir.create("raster_files",showWarnings = FALSE)
dir.create("mapping_files",showWarnings = FALSE)
dir.create("raw_shape_files",showWarnings = FALSE)
dir.create("gcam_boundaries_moirai_3p1_0p5arcmin_wgs84",showWarnings = FALSE)

#Declare all variables
Land_Data_Binary<-GLU<-GLU_Data<-shp_metadata<-shp_file<-shape_data<-shape_data_region<-shape_data_country<-Land_Data_Actual<-GLU_Data_Join<-
  GLU_Data_Join_Noland<-GLU_raster<-t<-t_noland<-NULL


#Declare parameters
#TODO When writing the function, use these as parameters
moirai_land_raster_path <-'input_files/moirai_valid_land_area.bsq'
moirai_basin_boundary_path <-"input_files/Global235_CLM_5arcmin.bil"
moirai_projection <- "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
gcam_region_boundaries <-'input_files/GCAM_32_w_Taiwan.shp'
#This is the threshold in m2 above which all holes will be filled in the vector files.
hole_filling_threshold <- 1e+19
#Following combinations can be generated by the code.
#1. Country
#2. region_ID
#3. GLU_ID (basin)
#4. Ctry_basin
#5. Reg_basin
#6. Reg_Ctry
raster_combinations <- c("Country","region_ID","GLU_ID","Ctry_basin","Reg_basin","Reg_ctry")

#--------------Step 1: Get land raster data from MOIRAI------------------------------------------------
Land_Data_Binary <- raster(moirai_land_raster_path)


#Step 2: Get basin boundaries
GLU <- raster(moirai_basin_boundary_path)
#Standardize basin raster to land raster
raster::projection(GLU)<-moirai_projection
raster::extent(GLU)<-extent(Land_Data_Binary)
#Get GLU_Data
GLU_Data<- as.data.table(rasterToPoints(GLU))
GLU_Data %>% rename(GLU_ID=Global235_CLM_5arcmin)->GLU_Data
rm(GLU)
#Part 2a: Get shape_file
#Read in shape file
shp_file<-shapefile(gcam_region_boundaries)
#Get metadata for later
shp_metadata <- st_as_sf(shp_file)
shp_metadata<-as.data.frame(shp_metadata)%>% mutate(GCAM_30_re=as.integer(GCAM_30_re))
#Standradize extent
shp_file@bbox <- as.matrix(extent(Land_Data_Binary))
#Convert to sf object before filling holes
shp_file <- st_as_sf(shp_file)
#Remove holes
shp_file<-smoothr::fill_holes(shp_file, threshold = hole_filling_threshold)
#Convert back to spatial polygons data frame
shp_file <- as(shp_file,"Spatial")

#2b Get region boundaries
shape_data <- rasterize(shp_file,Land_Data_Binary,field="GCAM_30_re")
shape_data_region <- as.data.table(rasterToPoints(shape_data))
shape_data_region<-filter(shape_data_region,layer>0) %>% rename(region_ID=layer)

#2b Get country boundaries
shape_data_country <- rasterize(shp_file,Land_Data_Binary,field="ISO_NUM")
shape_data_country <- as.data.table(rasterToPoints(shape_data_country))
shape_data_country<-filter(shape_data_country,layer>0) %>% rename(Country=layer)



rm(shp_file)
rm(shape_data)
gc()

#3 Now get land data
Land_Data_Actual <- (as.data.table(rasterToPoints(Land_Data_Binary)))

#Free some space
gc()




#Join in Land data and region names and get GCAM cells with no land
shape_data_country %>%
             #Join in GLU data
             left_join(GLU_Data, by=c("x","y")) %>%
             #Join in region boundaries
             left_join(shape_data_region,by=c("x","y")) %>%
             #Join in Land data
             left_join(Land_Data_Actual, by=c("x","y")) %>%
             mutate(moirai_valid_land_area=ifelse(is.na(moirai_valid_land_area),1,NA)) %>%
             na.omit() ->t_noland


#Get data with land
shape_data_country %>%
  #Join in GLU data
  left_join(GLU_Data, by=c("x","y")) %>%
  #Join in region boundaries
  left_join(shape_data_region,by=c("x","y")) %>%
  #Join in land data
  left_join(Land_Data_Actual, by=c("x","y")) %>%
  #Drop no land cells
  na.omit() ->t


rm(Land_Data_Actual)
rm(shape_data_country)
rm(shape_data_region)
rm(GLU_Data)

#Use this loop to generate the final rasters for land and no land
#1. Country
#2. region_ID
#3. GLU_ID (basin)
#4. Ctry_basin
#5. Reg_basin
#6. Reg_Ctry

for(i in raster_combinations){
t %>%select(-moirai_valid_land_area) %>% na.omit() %>% mutate(Ctry_basin=Country*1000+GLU_ID,
                                                              Reg_basin=region_ID*1000+GLU_ID,
                                                              Reg_Ctry=region_ID*1000+Country) %>%
                                                              select(i,x,y) %>%
                                                              rename(key=i) %>%
                                                              select(x,y,key)->GLU_Data_Join


t %>%select(-moirai_valid_land_area) %>% na.omit() %>% mutate(Ctry_basin=Country*1000+GLU_ID,
                                                              Reg_basin=region_ID*1000+GLU_ID,
                                                              Reg_Ctry=region_ID*1000+Country) %>%select(i,x,y,Country,GLU_ID,region_ID) %>%
                                                              rename(key=i,ctry_id=Country,basin_id=GLU_ID,reg_id=region_ID) %>% distinct()->mapping_data


write.csv(mapping_data,paste0("mapping_files/",toString(i),"_mapping.csv"),row.names = FALSE)

t_noland %>%select(-moirai_valid_land_area) %>% na.omit() %>% mutate(Ctry_basin=Country*1000+GLU_ID,
                                                                     Reg_basin=region_ID*1000+GLU_ID,
                                                                     Reg_Ctry=region_ID*1000+Country) %>%
                                                                     select(i,x,y) %>%
                                                                     rename(key=i)->GLU_Data_Join_Noland
#Land
coordinates(GLU_Data_Join)<-~x+y
gridded(GLU_Data_Join)<-TRUE
GLU_raster <-raster(GLU_Data_Join)
raster::projection(GLU_raster)<-"+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
GLU_raster<-raster::extend(GLU_raster,Land_Data_Binary)
writeRaster(GLU_raster, filename=tolower(paste0("raster_files/gcam_",toString(i),"_boundaries_moirai_land_cells_3p1_0p5arcmin.tif")), format="GTiff", overwrite=TRUE)

#No land
coordinates(GLU_Data_Join_Noland)<-~x+y
gridded(GLU_Data_Join_Noland)<-TRUE
GLU_raster <-raster(GLU_Data_Join_Noland)
raster::projection(GLU_raster)<-"+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
GLU_raster<-raster::extend(GLU_raster,Land_Data_Binary)
writeRaster(GLU_raster, filename=tolower(paste0("raster_files/gcam_",toString(i),"_boundaries_moirai_no_land_3p1_0p5arcmin.tif")), format="GTiff", overwrite=TRUE)

#Combined
GLU_Combined <- rbind(GLU_Data_Join_Noland,GLU_Data_Join)
gridded(GLU_Combined)<-TRUE
GLU_raster <-raster(GLU_Combined)
raster::projection(GLU_raster)<-"+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
GLU_raster<-raster::extend(GLU_raster,Land_Data_Binary)
writeRaster(GLU_raster, filename=tolower(paste0("raster_files/gcam_",toString(i),"_boundaries_moirai_Combined_3p1_0p5arcmin.tif")), format="GTiff", overwrite=TRUE)


print(paste0("Done generating rasters for land ,no land and combined for ",toString(i)))

}

#Remove data to free space
rm(t)
rm(t_noland)
rm(GLU_Data_Join)
rm(GLU_Data_Join_Noland)
rm(GLU_raster)


--------------#Step 2: Get raw shape files from rasters using polygonization code------------------------------------------------

#To polygonize these rasters (get shapefiles from them), use the following gdal command
#gdal_polygonize.py raster_name.tif shape_file_name.shp key key

#Define parameters
print("Please make sure that OSGeo is installed on your computer along with the requisite python bindings.
      This is required for the polygonization code.This can be downloaded here -https://www.osgeo.org/projects/osgeo4w/"
      )

osgeopath<-"c:/OSGeo4W64/OSGeo4W.bat"

raster_file_names <-list.files(path="raster_files/", full.names=TRUE,pattern = ".tif")

for (i in raster_file_names){

raster_name <- gsub(".tif","",i)
raster_name <- gsub("raster_files/","",raster_name)
system2(osgeopath,paste0("gdal_polygonize raster_files/",toString(raster_name),".tif raw_shape_files/",toString(raster_name),".shp key key"))

print(paste0("Completed processing shapefile- ",toString(raster_name),".shp"))
}

#------------------------Step 3: Add metadata-------------------------------------------------
#parameters
gcam_region_name_file <- "input_files/GCAM_region_names.csv"
gcam_iso_reg_id_file <-  "input_files/iso_GCAM_regID.csv"
gcam_basin_data_file <- "input_files/basin_to_country_mapping.csv"


#Get additional metadata: GCAM_region names
#Skip metadata rows when reading in csv
GCAM_region_names<-read.csv(gcam_region_name_file,skip = 6) %>% rename(Region_ID=GCAM_region_ID)
#Get additional metadata: basin_names
#Skip metadata rows when reading in csv
ISO_GCAM_REG_ID<-read.csv(gcam_iso_reg_id_file,skip = 6) %>% rename(Region_ID=GCAM_region_ID)

#Skip metadata rows when reading in csv
consolidated_data<-read.csv(gcam_basin_data_file,skip = 7) %>%
  mutate(iso=tolower(ISO)) %>%
  left_join(ISO_GCAM_REG_ID, by=c("iso")) %>%
  na.omit() %>%
  distinct() %>%
  rename(reg_nm=region_GCAM3,ctry_nm=country_name,basin_nm=Basin_name) %>%
  select(GCAM_basin_ID,ISO_NUM,Region_ID,basin_nm,ctry_nm,reg_nm) %>%
  rename(basin_id=GCAM_basin_ID,ctry_id=ISO_NUM,reg_id=Region_ID)

shp_metadata<-as.data.frame(shp_metadata)

ctry_data<-shp_metadata %>%
           rename(ctry_nm=ISOSHRTNAM,ctry_id=ISO_NUM) %>%
           select(ctry_nm,ctry_id) %>%
           mutate(key=ctry_id) %>%
           distinct()

reg_data <- shp_metadata %>%
            rename(reg_id=GCAM_30_re) %>%
            select(reg_id) %>%
            left_join(GCAM_region_names %>% rename(reg_id=Region_ID,reg_nm=region),by=c("reg_id")) %>%
            mutate(key=reg_id) %>%
            distinct()

basin_data<-consolidated_data %>%
            select(basin_id,basin_nm) %>%
            mutate(key=basin_id) %>%
            distinct()

ctry_basin_data<-read.csv("mapping_files/Ctry_basin_mapping.csv",stringsAsFactors = FALSE) %>%
                 select(ctry_id,basin_id,key) %>%
                 distinct() %>%
                 left_join(ctry_data %>% select(ctry_id,ctry_nm),by=c("ctry_id")) %>%
                 left_join(basin_data%>% select(basin_id,basin_nm),by=c("basin_id")) %>%
                 select(basin_nm,ctry_nm,key,basin_id,ctry_id) %>%
                 distinct()

reg_basin_data<-read.csv("mapping_files/Reg_basin_mapping.csv",stringsAsFactors = FALSE) %>%
                select(reg_id,basin_id,key) %>%
                distinct() %>%
                left_join(basin_data%>% select(basin_id,basin_nm),by=c("basin_id")) %>%
                left_join(reg_data%>% select(reg_id,reg_nm),by=c("reg_id")) %>%
                select(key,basin_nm,reg_nm,basin_id,reg_id) %>%
                distinct()

reg_ctry_data<-read.csv("mapping_files/Reg_Ctry_mapping.csv",stringsAsFactors = FALSE) %>%
               select(reg_id,ctry_id,key) %>%
               mutate(reg_id=as.integer(reg_id),ctry_id=as.integer(ctry_id)) %>%
               distinct() %>%
               left_join(ctry_data%>% select(ctry_id,ctry_nm),by=c("ctry_id")) %>%
               left_join(reg_data%>% select(reg_id,reg_nm),by=c("reg_id")) %>%
               distinct()

#Get all filenames
file_names<- list.files(path="raw_shape_files/", full.names=TRUE,pattern = ".shp")

for (i in file_names){
Final_shape_file<- shapefile(toString(i))

file_name<- gsub("raw_shape_files/","",i)
file_name<-gsub("gcam_","",file_name)
file_name<-gsub(".shp","",file_name)
print(paste0("Completed processing ",toString(file_name)))
Final_shape_file <- st_as_sf(Final_shape_file)

#If its a combined file,fill holes
if(grepl("combined",file_name)){

  Final_shape_file<-smoothr::fill_holes(Final_shape_file, threshold = hole_filling_threshold)}

if (grepl("country",file_name)){
  Final_shape_file %>% inner_join(ctry_data, by=c("key"))->Final_shape_file
  tmpna<-Final_shape_file[is.na(Final_shape_file$ctry_nm),]
  # Note that first 10 rows are meatadata rows. Hence the code checks for rows higher than 10.
  if (length(tmpna)>10){

    print(paste0("Na values found in ",toString(i)))
          print(tmpna)
  }

}


if (grepl("glu_id",file_name)){
  Final_shape_file %>% inner_join(basin_data, by=c("key"))->Final_shape_file
  tmpna<-Final_shape_file[is.na(Final_shape_file$basin_nm),]
  # Note that first 10 rows are meatadata rows. Hence the code checks for rows higher than 10.
  if (length(tmpna)>10){
    print(paste0("Na values found in ",toString(i)))
          print(tmpna)
  }

  }


if (grepl("region_id",file_name)){
  Final_shape_file %>% inner_join(reg_data, by=c("key"))->Final_shape_file

  tmpna<-Final_shape_file[is.na(Final_shape_file$reg_nm),]
  # Note that first 10 rows are meatadata rows. Hence the code checks for rows higher than 10.
  if (length(tmpna)>10){
    print(paste0("Na values found in ",toString(i)))
          print(tmpna)
  }
}

if (grepl("ctry_basin",file_name)){
  Final_shape_file %>% inner_join(ctry_basin_data, by=c("key"))->Final_shape_file
  # Note that first 10 rows are meatadata rows. Hence the code checks for rows higher than 10.
  tmpna<-Final_shape_file[is.na(Final_shape_file$ctry_nm),]
  if (length(tmpna)>10){
    print(paste0("Na values found in ",toString(i)))
          print(tmpna)
  }

}



if (grepl("reg_basin",file_name)){
  Final_shape_file %>% inner_join(reg_basin_data, by=c("key"))->Final_shape_file
  # Note that first 10 rows are meatadata rows. Hence the code checks for rows higher than 10.
  tmpna<-Final_shape_file[is.na(Final_shape_file$reg_nm),]
  if (length(tmpna)>10){
    print(paste0("Na values found in ",toString(i)))
          print(tmpna)
          print(length(tmpna))
  }

}

if (grepl("reg_ctry",file_name)){
  Final_shape_file %>% inner_join(reg_ctry_data, by=c("key"))->Final_shape_file
  # Note that first 10 rows are meatadata rows. Hence the code checks for rows higher than 10.
  tmpna<-Final_shape_file[is.na(Final_shape_file$ctry_nm),]
  if (length(tmpna)>10){
    print(paste0("Na values found in ",toString(i)))
          print(tmpna)
  }

}

#Test for 2 exceptions: 3 sided polygons, self intersections
exceptions<-st_is_valid(Final_shape_file,NA_on_exception = TRUE)
na_exceptions<-exceptions[is.na(exceptions)]
self_intersections <-exceptions[exceptions=="FALSE"]

if(length(na_exceptions)>0){
  print("Fixing invalid geometries")
  Final_shape_file<-st_make_valid(Final_shape_file)

}

if(length(self_intersections)>0){
  print("Fixing self intersections")
  Final_shape_file<-st_make_valid(Final_shape_file)

}
#Final clean ups
file_name <- gsub("land_cells","landcells",file_name)
file_name <- gsub("no_land","noland",file_name)
file_name <- gsub("region_id","region",file_name)
file_name <- gsub("glu_id","basin",file_name)

Final_shape_file <- as(Final_shape_file,"Spatial")
Final_shape_file <- raster::aggregate(Final_shape_file,names(Final_shape_file))
writeOGR(Final_shape_file, dsn = 'gcam_boundaries_moirai_3p1_0p5arcmin_wgs84', layer = toString(file_name), driver = "ESRI Shapefile",overwrite_layer = TRUE)

}

print("Completed generating rasters, vectors and mapping files.")




